# Generated by Django 3.2.13 on 2022-06-20 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='company',
            new_name='stock_code',
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stock_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathon.users')),
            ],
        ),
    ]
