# Generated by Django 3.2.13 on 2022-06-20 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0003_auto_20220620_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Q1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='Q2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='Q3',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='Q4',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='Q5',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='Q6',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='Q7',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='Q8',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='Q9',
            field=models.CharField(max_length=100),
        ),
    ]
