# Generated by Django 3.2.13 on 2022-06-21 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0004_auto_20220621_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Q10',
            field=models.CharField(max_length=100),
        ),
    ]
