# Generated by Django 4.0.5 on 2022-06-21 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0005_alter_users_q10'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Q1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='Q2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='Q3',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='Q4',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='Q5',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='Q6',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='Q7',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='Q8',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='Q9',
            field=models.IntegerField(),
        ),
    ]
